### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by tearodactyl** [zerocurrencycoin/Zero#13]
In anticipation of the hard fork, methods of controlling such behaviors within Zcash clones were reviewed.

The Zero fork will cover a number of changes, particularly how the miner block reward is computed, but also will adjust various parameters to improve resistance to various types of attacks. Nevertheless, new issues are likely to come up and we may find it necessary to tweak some of the changes, so a second fork may well take place before the year is out.

Nodes communicate to each other the feature sets they support via the initial exchange of [Version](https://en.bitcoin.it/wiki/Protocol_documentation#version) information. Zcash inherited from Bitcoin some of the basic methods, like "[version bits](https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki)".

Around Zcash 1.0.15 was introduced a new system of tracking versions and activation height (block number), by creating _struct_ [NetworkUpgrade](https://github.com/zcash/zcash/blob/v1.1.2/src/consensus/params.h).
Files affected, not including a whole bunch of unit tests:
```
chainparams.h
chainparams.cpp
init.cpp
main.cpp
rpcblockchain.cpp
rpcrawtransaction.cpp
zcbenchmarks.cpp
consensus/params.h
consensus/upgrades.h
consensus/upgrades.cpp
```

ProtocolVersion values defined already:
```
BASE 170002
OVERWINTER 170005
SAPLING 170007
OVERWINTER nActivationHeight 347500
```

Clones have taken a simpler route and added specific fields directly to the consensus and ChainParams classes, say [Snowgem](https://github.com/Snowgem/Snowgem/blob/master/src/chainparams.cpp) consensus.nMasternodePaymentsStartBlock and  newTimeRule eh_epoch_1_endblock. eh_epoch_2_startblock.
Files affected:
```
chainparams.h
chainparams.cpp
pow.cpp
```

[BTCG similarly](https://github.com/BTCGPU/BTCGPU/blob/master/src/chainparams.cpp) has added BTGZawyLWMAHeight and BTGEquihashForkHeight
Files affected:
```
chainparams.h
chainparams.cpp
pow.cpp
consensus/params.h
```

Disregard all the added complexity with versions and blocks that they have inherited from Bitcoin.
They do have [test automation](https://github.com/BTCGPU/BTCGPU/pull/315/commits/b745ea4bb565b6ec2e0756634bd10875de20c216) for the fork.

Zen has been forking since its split from Zclassic and keeps at it. They have created the most advanced system, where fork parametrization is externalized to a file, though a bunch of .CPP support is still necessary. Their case in a sense is closest to ours, as they have re-introduced the fee, after Zclassic removed it. But since they also have different kinds of nodes and been tweaking the fee allocation between them, their code is more involved than what we are going to have.

We may choose to go through two transitions in the fork, first permit new format blocks (with the fee) and later disallow the old format, to smooth out the transition. We would then want a command line option to alter this behavior, if we find the network lagging in adoption and need to delay upgraded nodes from stepping through the transitions.

Pick the level of fork code complexity that fits our anticipated requirements and implement it as a separate set of functionality within Zero codebase.

**Comment by tearodactyl** [comment]
An example of extensive documentation on handling a fork, addressing a number of different user populations https://github.com/BTCGPU/BTCGPU/issues/331

**Comment by CryptoForge** [comment]
I've reviewed the options and chose to code the fork using the snowgem model for simplicity and mergability sake. The change to reincorporate the halving and fee structure only requires a single new field and leaves the ability to merge into zcash 1.0.15 easier.

**Comment by R3DEY3UK** [comment]
Proposed naming for fork - **Uummannaq** _(Sugar Loaf Island)_ 

https://en.wikipedia.org/wiki/Sugar_Loaf_Island

**Comment by CryptoForge** [comment]
Completed as of 1.0.14-2.
