### ISSUE TITLE
Fee

### ISSUE THREAD

**Issue by tearodactyl** [zerocurrencycoin/Zero#16]
Development Fee (AKA Founder Reward) was built into the original Zcash codebase and the coins with a fee (Hush, Snowgem, Zen) all use same code structure. Zclassic and Zero have that code removed. Many places in the codebase may be affected by this change, and we need to handle the transition first to allow new blocks and then rejecting them. Nevertheless, bringing the code back, which revolves around the FoundersReward fields of the [CChainParams class](https://github.com/zcash/zcash/blob/master/src/chainparams.h), is a separable task that can be validated on a dedicated testnet.

Since Zcash Reward is scheduled to end after four years, they already have a field consensus.GetLastFoundersRewardBlockHeight. We would add one for the starting height and use it in all the same places in the code.

**Comment by CryptoForge** [comment]
Completed as of version 1.0.14-2
