### ISSUE TITLE
Merge Upstream Fixes

### ISSUE THREAD

**Issue by tearodactyl** [zerocurrencycoin/Zero#20]
There are improvements and fixes from many upstream codebases, Bitcoin and Zcash and various libraries that they use.  Also, fellow Z clones may post something useful or essential.

Need to track and integrate such fixes, commits, and PRs on regular basis. Currently candidate changes are tracked internally via a spreadsheet. For the ones that may benefit from public review and to encourage the entire community and contributors to submit more candidates, will list current list as a group or individually, as warranted by the subject matter and their degree of complexity.

For consideration
https://github.com/BTCGPU/BTCGPU/pull/334/commits/2513b618a3c8813e3b2c61f5ece46eebc109ebca

Do we need such a tool? https://github.com/BTCGPU/equihashjs-verify

**Comment by tearodactyl** [comment]
Zcash PRs considered for a merge
```
#2977	https://github.com/zcash/zcash/pull/2977/files	Check Equihash solution when loading block index #2977
#2993	https://github.com/zcash/zcash/pull/2993/files	Use block hash comparison for consistency check when loading block index #2993
#2839	https://github.com/zcash/zcash/pull/2839/files	Add getdeprecationinfo RPC method to return deprecation block height #2839
#2808	https://github.com/zcash/zcash/pull/2808/files	Add network upgrade details to getblockchaininfo #2808
#2931	https://github.com/zcash/zcash/pull/2931/files	read hashReserved from disk #2931
```

**Comment by CryptoForge** [comment]
Completed with upmerge to 2.0.1
