### ISSUE TITLE
Time-Stamp Attack 

### ISSUE THREAD

**Issue by R3DEY3UK** [zerocurrencycoin/Zero#28]
https://github.com/zawy12/difficulty-algorithms/issues/30.
We would need to reduce the fix Snowgem installed (which was for this issue) from **10 minutes** to **6 minutes.** The recommendation is **300 (5 min) or N*T/20 (60*120/20=360 or 6 min)** whichever is greater.

**Comment by tearodactyl** [comment]
6 min is pretty tight, only three block times.

**Comment by tearodactyl** [comment]
Not to discount its importance, but it is tracked as a subset of #17
