### ISSUE TITLE
Track RSK 

### ISSUE THREAD

**Issue by R3DEY3UK** [zerocurrencycoin/Zero#43]
We should have a good in-depth look into RSK, learning how Zero can add "Smart Contract" functionality in the future. 

[RSK](https://www.rsk.co/) is the first open-source smart contract platform with a 2-way peg to Bitcoin that also rewards the Bitcoin miners via merge-mining, allowing them to actively participate in the Smart Contract revolution. RSK goal is to add value and functionality to the Bitcoin ecosystem by enabling smart-contracts, near instant payments and higher-scalability.

**Comment by CryptoForge** [comment]
Moved to Projects
