### ISSUE TITLE
BIP44 Coins

### ISSUE THREAD

**Issue by tearodactyl** [zerocurrencycoin/Zero#46]
At some point we picked-up a Zcash change around line 85 of chainparams.cpp:
`bip44CoinType = 133; // As registered in https://github.com/satoshilabs/slips/blob/master/slip-0044.md`

133 is a value that Zcash reserved and we should probably have one for Zero. This only affects what some wallets could learn through the RPC interface.

**Comment by CryptoForge** [comment]
Zero registered with satoshi labs, bip44 #323. Cobes has been updated. https://github.com/zerocurrencycoin/Zero/commit/e2190bb9cb449fdfbf9680b11b49248f31835e0a
